version: '3.9'

services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_with_spring_boot
      TZ: America/Sao_Paulo
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - elton-network
  rest-with-spring-boot:
    image: notleamil/rest-with-spring-boot-and-java
    build: ./rest-with-spring-boot-and-java
    working_dir: /rest-with-spring-boot-and-java
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    command: mvn spring-boot:run
    networks:
      - elton-network
    depends_on:
      - db
networks:
  elton-network:
    driver: bridge