spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
cors:
  originPatterns: http://localhost:8080,https://erudio.com.br,http://localhost:3000
file:
  upload-dir: /Users/notle/Downloads/workspace-spring-tool-suite-4-4.22.1.RELEASE/rest-with-spring-boot-and-java/uploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
server:
  port: 80